model_bucket = "prod-mlflow-models"
lambda_function_local_path = "../lambda_function.py"
docker_image_local_path = "../Dockerfile"
ecr_repo_name = "prod_mobile_phone"
lambda_function_name = "prod_prediction_lambda"